# Generated by Django 6.1 on 2026-08-17 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipodocumentoconfig',
            name='area_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.rol'),
        ),
    ]
